# Generated by Django 5.0.6 on 2024-05-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threevennproblemstatementmodel',
            name='field3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
