# Generated by Django 4.2 on 2024-10-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_submissioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsubmission',
            name='problem_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='channelsubmission',
            name='channel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.roomchannel'),
        ),
        migrations.AlterField(
            model_name='channelsubmission',
            name='submitted_work',
            field=models.FileField(upload_to=''),
        ),
    ]
