# Generated by Django 5.0.6 on 2024-05-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_threevennproblemstatementmodel_field3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threevennproblemstatementmodel',
            name='field3',
        ),
    ]
