# Generated by Django 5.0.6 on 2024-06-02 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_threevennproblemstatementmodel_field3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThreeVennDiagram',
            new_name='ThreeVennDiagramModel',
        ),
        migrations.RenameModel(
            old_name='TwoVennDiagram',
            new_name='TwoVennDiagramModel',
        ),
    ]
