# Generated by Django 5.0.6 on 2024-10-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_submissionvoting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmissionVoting',
            new_name='SubmissionVotingMark',
        ),
    ]
