# Generated by Django 5.0.6 on 2024-10-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_submissionvoting_submissionvotingmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsubmission',
            name='submitted_work',
            field=models.URLField(),
        ),
    ]
