# Generated by Django 4.2 on 2024-10-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_author'),
        ('api', '0004_rename_submissionvoting_submissionvotingmark'),
    ]

    operations = [
    ]
