# Generated by Django 4.2 on 2024-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_channelsubmission_submitted_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelsubmission',
            name='submitted_work_content',
        ),
        migrations.RemoveField(
            model_name='channelsubmission',
            name='submitted_work_name',
        ),
        migrations.RemoveField(
            model_name='channelsubmission',
            name='submitted_work_type',
        ),
        migrations.AddField(
            model_name='channelsubmission',
            name='submitted_work',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
