# Generated by Django 5.0.6 on 2024-11-04 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_channelsubmission_submitted_work'),
        ('api', '0007_remove_channelsubmission_submitted_work_content_and_more'),
    ]

    operations = [
    ]
